# Generated by Django 5.2 on 2025-06-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_solution_rename_summary_news_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.SlugField(blank=True, help_text='Stock Keeping Unit', unique=True),
        ),
    ]
